### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by JakubOnderka** [seanmonstar/spmc#4]
Hi, I have a problem with memory leaks with your library. Data are not removed from memory after receiving from spmc rx channel. Simple example:

```rust
extern crate spmc;

use std::io;

fn main() {
    let (tx, rx) = spmc::channel();

    for i in 0..1000000 {
        tx.send(format!("Ahoj svete {}", i)).unwrap();
    }
    drop(tx);

    // Memory usage at this location: ~62 MB
    let mut input = String::new();
    io::stdin().read_line(&mut input).unwrap();

    loop {
        match rx.recv() {
            Ok(_) => continue,
            Err(_) => break,
        }
    }

    // Memory usage at this location: ~62 MB
    let mut input = String::new();
    io::stdin().read_line(&mut input).unwrap();
}
```

**Comment by seanmonstar** [comment]
This test suggests they are indeed dropped: https://github.com/seanmonstar/spmc/commit/6a0942fe2ed4f57c07e94c2c1da2f001f393a6f0

**Comment by RouquinBlanc** [comment]
Indeed, seems to leak...
```rust
extern crate spmc;

fn main() {
    loop {
        let (tx, rx) = spmc::channel();

        for i in 0..1000000 {
            tx.send(format!("Ahoj svete {}", i)).unwrap();
        }
        drop(tx);

        loop {
            match rx.recv() {
                Ok(_) => continue,
                Err(_) => break,
            }
        }
    }
}
```
This uses very quickly several GB of memory... Could it be possible that the value itself is dropped correctly, but not the underlying Node?

**Comment by RouquinBlanc** [comment]
Adding this:
```rust
impl<T> Drop for Node<T> {
    fn drop(&mut self) {
        println!("Node dropped");
    }
}
```
It seems to be never called...

**Comment by RouquinBlanc** [comment]
Looking at this VERY interesting post: https://aturon.github.io/blog/2015/08/27/epoch/

It describes the same kind of problematics. And in their example, they state that the call to `compare_and_swap` will leak the Node!

If I replace the code in Queue.pop() by this:
```rust
                    if node == self.head.compare_and_swap(node, next, Ordering::SeqCst) {
                        let value = (*node).value.take();
                        mem::drop(Box::from_raw(node));
                        return value;
                    }
```
... The code added above to print on Node dropping gets called, and memory does not seem to leak anymore. But as I suspect some [even bigger problems](https://github.com/seanmonstar/spmc/issues/5), the whole code may require some rework

**Comment by seanmonstar** [comment]
Indeed, that was it. The `*mut Node` was never freed. It wasn't quite as simple as just sticking `from_raw` in, as care needed to be taken to not drop the `Node` while another receiver might be inspecting it. Unfortunately, that required an additional swap loop, to make sure only 1 thread could ever inspect and then drop the `Node` at a time. I've pushed the fix to master, and will publish shortly.
